# Generated by Django 5.0.4 on 2024-04-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moshina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moshina_name', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
